### ISSUE TITLE
The HammingWeight of CalculateDctHash() is always an even number

### ISSUE THREAD

**Issue by daviddennisei** [Quickshot/DupImageLib#7]
I'm not sure if this is a bug, or expected behavior, but when I created a 64 entry histogram of the "onesInHash" of a large number (> 1.5 million) of CompareHashes() results, I noticed that all the odd-numbered entries were zero. Investigating further, I discovered  the HammingWeight of all 1779 results returned from CalculateDctHash(0 were also even numbers. I don't understand the DctHash algorithm well enough to judge, but this feels like a bug to me. Instead of 65 possible comparison results, we only have 33. 

I wrote the attached test program to convince myself that I hadn't introduced a subtle bug into your code.  I downloaded a fresh copy of your latest code, added a new console project to it, and replaced the auto-generated Program.cs with my test app.  To run it, replace the first line of Main() with a path to a folder containing a bunch of image files.
[Program.zip](https://github.com/Quickshot/DupImageLib/files/5811296/Program.zip)

**Comment by Quickshot** [comment]
I went throught the DCT hash generation and it seems to be correct. I also tested the DCT calculation part against another implementation and it gave identical results to my implementation. Thus it seems that this somewhat strange behaviour is just how DCT hash calculation functions.

In future versions I will probably extend the DCT hash generation to also produce 128-bit hashes to take care of this loss of precision.

**Comment by jeffward01** [comment]
> I went throught the DCT hash generation and it seems to be correct. I also tested the DCT calculation part against another implementation and it gave identical results to my implementation. Thus it seems that this somewhat strange behaviour is just how DCT hash calculation functions.
> 
> In future versions I will probably extend the DCT hash generation to also produce 128-bit hashes to take care of this loss of precision.

Is this as simple as replacing all of the `64`  values with `128`? [See code here](https://github.com/Quickshot/DupImageLib/blob/master/DupImageLib/ImageHashes.cs)

I can create a pull request if so.

Do you know anything about this version of PHash made by the student of the doctor who create the algo? [FindSimilar](https://github.com/dlaperriere/Find_Similar_Images/blob/master/Library/Image/ImageHash/ImagePHash.cs)

Thanks for this AWESOME library!

**Comment by davidei1955** [comment]
It's almost certainly not as easy as replacing 64 with 128. The code relies on the fact that a C# ulong is 64 bits long. .NET 7 will have a UINT128 datatype, but it's only available in (bleeding edge) .NET 7 Preview 5. Testing I did several years ago on a Java pHash package indicated that 64-bit DCT hashes were only marginally worse than 256-bit DCT hashes and much faster to create. YMMV.
FWIW, I read somewhere that odd-numbered  "onesInHash" being zero is expected behavior for DCT algorithms. It's apparently caused by the fact that the algorithm uses cosine and cosine(pi/2) = 0.

**Comment by jeffward01** [comment]
> It's almost certainly not as easy as replacing 64 with 128. The code relies on the fact that a C# ulong is 64 bits long. .NET 7 will have a UINT128 datatype, but it's only available in (bleeding edge) .NET 7 Preview 5. Testing I did several years ago on a Java pHash package indicated that 64-bit DCT hashes were only marginally worse than 256-bit DCT hashes and much faster to create. YMMV. FWIW, I read somewhere that odd-numbered "onesInHash" being zero is expected behavior for DCT algorithms. It's apparently caused by the fact that the algorithm uses cosine and cosine(pi/2) = 0.

That's extremely interesting!  Thank you for replying so fast, this is very helpful.



Yea, I figured that it was not as simple as simply changing the bytesize for 64 to 128, but I figured that I do not know much about low-level of hash generation so I might as well ask and see.

It sounds like PHash is optimized for 64 bit hashes, and that the value add based on your research is not worth it.  Perhaps when the new net7.0 is stable (probably best not to touch bleeding edge imo) maybe the case will be different.

But I suspect that your research is 1000% correct, and based on ` cosine and cosine(pi/2) = 0` has a large reason of why this is the case.

Perhaps we'll have to wait until PHash2 comes out, like Blake2 and Blake3 eventually were published.

Big thank you again on the response! I write code all day, every day, mainly infrastructure microservice type code, and reading your response makes me realize I have much to learn in the areas of hashing and byte hashing!

Again, big thank you for this amazing library!

---

**Off topic Questions (I can open up separate issues if needed**

1.  In the past did you work with the other C# PHash Implementation called [FindSimilar](https://github.com/dlaperriere/Find_Similar_Images/blob/master/Library/Image/ImageHash/ImagePHash.cs)? I am curious about the performance differences (if any) because the implementation is different (perhaps its the same, but the code is much different).
    *  At some point in the future I want to create a 'benchmark comparison' for this library and  [FindSimilar](https://github.com/dlaperriere/Find_Similar_Images/blob/master/Library/Image/ImageHash/ImagePHash.cs) just for curiosities sake

2. Do you consider `DupImageLib` to be complete? Or is there a roadmap / Feature wishlist? I'd love to make some pull requests.

Thanks again!

**Comment by daviddennisei** [comment]
I’ve never worked with FindSimilar. I think DupImageLib is pretty good. I like the fact that it has 4 different pHash algorithms and pluggable transformers to greyscale and shrink the images. The other 3 algorithms are significantly faster than DctHash. My limited testing indicates that they all perform pretty well, with DctHash usually at or near the top in match quality.

 

I suspect that the most important difference between pHash implementations will come down to the algorithm used to shrink the image.  I see that the author of DupImageLib has switched form Magick.Net to ImageSharp. I’ll be curious to see how they compare. 

The DctHash generation code itself is not very long or complex. My suspicion is that everybody has copied each other’s hashing code and there aren’t significant differences between them (except performance. DupImageLib uses Math.Consine(); I have a Java implementation that uses a table-lookup for its discrete cosine values, which should be a lot faster).



Note that DupImageLib’s DctHash generates a 64-bit hash code, as does its other 3 pHash algorithms.  The cosine thing just means that it classifies a comparison of two images into 1 of 32 ‘slots’ (from identical to not-at-all-similar), rather than 64 slots. Based on my testing, DctHash is most often the best classifier of the 4. AvgHash does pretty well, too. My testing is on-going, and harder to do than you’d think, so this conclusion is somewhat provisional.

 

I’d like to see an implementation that hashes all three RGB channels, rather than grayscaling the image. 

 

 

Best regards,

 

David Ei

   Email:     ***@***.***> ***@***.***

   Home:  (734) 449-2404

   Cell:       (734) 353-9542
